name: 'build all'

on:
  workflow_dispatch:

env:
  REPO_URL: "https://registry.hub.docker.com/v2/namespaces/homeassistant/repositories/amd64-addon-silabs-multiprotocol/tags?page=1&page_size=1000"

jobs:
  provide_versions:
    name: provide base versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.tags.outputs.matrix }}
    steps:
      - name: get all tags
        id: tags
        run: echo matrix=$(curl -s '${{ env.REPO_URL }}' | jq -r '.results | reverse') >> $GITHUB_OUTPUT
      - name: count tags
        run: jq -r 'length' <<< '${{ steps.tags.outputs.matrix }}'

  call_build:
    runs-on: ubuntu-latest
    needs: provide_versions
    permissions: write-all
    strategy:
      max-parallel: 1
      matrix:
        include: ${{ fromJson(needs.provide_versions.outputs.matrix) }}
    name: trigger build for ${{ fromJSON(toJSON(matrix)).name }}
    steps:
      - name: Check
        env:
          VERSION: ${{ fromJSON(toJSON(matrix)).name }}
        run: |
          echo "VERSION: ${{ env.VERSION }}"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: container
          client-payload: '{"base_version": "${{ fromJSON(toJSON(matrix)).name }}"}'
